--- # Ansible playbook to provision instances for myself
- name: provisioning with Ansible
  hosts: all
  gather_facts: no
  become: true
  become_user: root
  tasks:

#    - apt: {update_cache: yes}
    - apt:
        dpkg_options: 'force-confold,force-confdef'
        name:
            - vim-nox
            - fish
            - nmon
            - silversearcher-ag
            - tree
            - git
            - openssh-client
            - bwm-ng
            - htop
#            - openjdk-9-jdk-headless
            - python3-virtualenv
            - python3-pip
            - mc
            - links
            - lynx
            - iptables-persistent
            - nmap
            - build-essential
            - cmake
            - ninja-build
            - curl
            - libatlas-base-dev
            - libjemalloc-dev
            - liblapack-dev
            - libopenblas-dev
            - libopencv-dev
            - libzmq3-dev
            - software-properties-common
            - sudo
            - unzip
            - wget
            - sysstat
            - awscli
            - ccache
    - apt:
        state: absent
        name:
            - btrfs-progs
            - btrfs-tools

#
# Wait for raid setup to finish
#

    - name: Wait for userdata to finish
      wait_for:
        path: /tmp/userdata_complete
        state: present
        timeout: 1200
        sleep: 3


#
# User setup
#

    - name: Add wheel group
      group:
        name: wheel
        state: present

    - name: Add user {{ user_name }} to group wheel
      user:
        name: "{{ user_name }}"
        groups: wheel
        shell: /bin/bash

    - name: sync homedir/ to /home/{{ user_name }}
      synchronize:
        src: homedir/
        dest: /home/{{ user_name }}/

    - name: Configure /home/{{ user_name }}
      file:
        path: /home/{{ user_name }}
        recurse: yes
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - file:
        path: /home/{{ user_name }}/.ssh/
        mode: 0700

#    - file:
#        path: /home/{{ user_name }}/.ssh/id_rsa
#        mode: 0600

    - name: set permissions in /home/{{ user_name }}/bin
      file:
        path: /home/{{ user_name }}/bin
        mode: "u=rwx,g=rx,o=rx"
        recurse: yes

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'


#
# Docker Install
#
    - command: lsb_release -cs
      register: lsb_release

    - debug:
        msg: "{{ lsb_release.stdout }}"

    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable

    - name: Create new docker data folder in /home/docker (uses ephemeral storage)
      file:
        path: /home/docker
        state: directory

    - name: Put docker images folder in /home
      mount:
        path: /var/lib/docker
        src: /home/docker
        fstype: none
        opts: bind
        state: mounted


    - apt:
        name:
            - docker-ce

    - user:
        name: "{{ user_name }}"
        groups: docker
        append: yes

    - pip:
        name: docker
        executable: pip3

    - apt: autoremove=yes

