--- # Ansible playbook
- name: copy hosts.txt file to all the nodes for mpirun
  hosts: all
  gather_facts: no
  become: true
  become_user: "{{ user_name }}"
  tasks:
    - name: copy hosts.txt to /home/{{ user_name }}
      copy:
        src: ../hosts.txt
        dest: /home/{{ user_name }}/hosts.txt
        owner: "{{ user_name }}"
        mode: 0644
